spring.config.import=optional:dotenv:./.env
spring.application.name=testequipux
spring.datasource.url=${SPRING_DATASOURCE_URL:}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true

nationality.api.base-url=${NATIONALITY_API_BASE_URL}

jwt.secret=${JWT_SECRET:ChangeThisJwtSecretKeyChangeThisJwtSecretKey}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.jdbc=DEBUG
